### ISSUE TITLE
[Crash] - 1.20.1 - neoforge-1.1.6

### ISSUE THREAD

**Issue by muggleorwizard** [st0x0ef/stellaris#41]
Crash Report: https://pastebin.com/sY6Uncf5
Log: https://pastebin.com/eCWg1Q5D
Mod List: https://pastebin.com/BWHHSjPs
Note: Crash occurs with stellaris-1.21-neoforge-1.1.6. Crash does not occur with stellaris-1.21-neoforge-1.1.5. Making a report on the almost unified github page as well (since they are mentioned in the crash). https://github.com/AlmostReliable/almostunified/issues/99
Crash occurred when clicking trying to create a new world.

**Comment by rlnt** [comment]
Considering you only changed a few tags and translations in the 1.1.6 update, I don't see how this crash could be related to Stellaris honestly. I am not sure what's happening in the first place.

The log shows the error recipe error collector method is called on Almost Unified. However, this is being invoked by a mixin in the recipe manager. It also shows that it's called on the client which causes the crash because our runtime doesn't exist on the client.

**Comment by rlnt** [comment]
Okay, I found the issue. The tag fix you introduced is wrong. You accidentally removed the raw steel instead of the raw steel block from this tag. https://github.com/st0x0ef/stellaris/commit/3c3a43d994515d9055431d776425fac94632e554#diff-7ce865e62be0b5624ae16d9598248d25b648395daeb5532c3e91ee2318a66f32

Edit: this should obviously not crash on our side and I need to handle this case but it was a good indicator that the tag is wrong lol

**Comment by TathanDev** [comment]
Thanks for indicating where the error was !
